version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    hostname: "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    hostname: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  solicitar:
    build: .    
    depends_on:
      - kafka
    volumes:
      - "./solicitar:/usr/src/app"
    command: python3 solicitar.py
    ports:
      - "5001:5000"
  
  horario:
    build: .
    depends_on:
      - kafka
    volumes:
      - "./horario:/usr/src/app"
    command: python3 horario.py
  
  quarto:
    build: . 
    depends_on:
      - kafka
    volumes:
      - "./quarto:/usr/src/app"
    command: python3 quarto.py

  agendar:
    build: . 
    depends_on:
      - kafka
    volumes:
      - "./agendar:/usr/src/app"
    command: python3 agendar.py
